export enum ListPermissions {
  CREATE_EXERCISE = 'create_exercise',
  GET_EXERCISES = 'get_exercises',
  UPDATE_EXERCISE = 'update_exercises',
  DELETE_EXERCISE = 'delete_exercises',
  CREATE_DIET = 'string',
  GET_DIET = 'get_diets',
  UPDATE_DIET = 'update_diets',
  DELETE_DIET = 'delete_diets',
  CREATE_CUSTOMER_AND_CUSTOMER_SPECIALIST = 'create_customer_and_customer_specialist',
  CREATE_CUSTOMER_SPECIALIST = 'create_customer_specialist',
  GET_ASSOCIATED_CUSTOMERS = 'get_associated_customers',
  CREATE_ROUTINE = 'create_routine',
  GET_ROUTINE = 'get_routines',
  UPDATE_ROUTINE = 'update_routines',
  DELETE_ROUTINE = 'delete_routine',
  GET_CUSTOMER_DETAILS = 'get_customer_details',
  GET_SPECIALIST_DETAILS = 'get_specialist_details',
}
